import { type NextPage } from "next";
import Head from "next/head";
import { useContext } from "react";
import Link from "next/link";
import { Navbar } from "../components/Navbar";
import { VideoPlayer } from "../components/VideoPlayer";
import PlayerContext  from "../contexts/PlayerContext";

const Home: NextPage = () => {
	const player = useContext(PlayerContext);

	return (
		<>
			<Head>
				<title>dr34m Radio</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#000000]" >
				<Navbar />
				<VideoPlayer isPlaying={player.isPlaying} />
			</main>
		</>
	);
};

export default Home;