import { type NextPage } from "next";
import Head from "next/head";
import { Main } from "../layouts/Main";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>dr34m Radio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <section className="min-h-[90vh] py-8">
          <h1>Faça login pra continuar</h1>
        </section>
      </Main>
    </>
  );
};

export default Home;
