import { type NextPage } from "next";
import Head from "next/head";
import { HomeDashboard } from "../components/HomeDashboard";
import { Main } from "../layouts/Main";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>dr34m Radio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <HomeDashboard />
      </Main>
    </>
  );
};

export default Home;
